Add test case for loading arm elf with thumb entry
Currently the test should fail, because rizin prints the following error.

ERROR: Cannot determine entrypoint, using 0x00010320.