Fix (partially) cross-compilation to Mips64.
'mips' is apparently a reserved keyword or macro in the mips64-linux-musl toolchain.
In any case, the build fails with things like:

error: invalid type argument of ‘->’ (have ‘int’)
 1515 |         const char *magic = ecoff_aouthdr_magic_to_string(mips->magic);

if 'mips' is used as a name.