librz/bin: avoid error for ARM ELFs with thumb entry (#5554)
* Add test case for loading arm elf with thumb entry

Currently the test should fail, because rizin prints the following error.

ERROR: Cannot determine entrypoint, using 0x00010320.

* Don't incorrectly log error for arm elfs

If there is a thumb instruction at entrypoint, the lowest bit in bin->ehdr.e_entry is set.
For tmp->vaddr the thumb bit is not present.

This patch removes the thumb bit before comparing both addresses.